site_name: SoundBrain Lab
copyright: Abril LM
theme:
  name: material

  palette:
    - scheme: slate #dark mode
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default #light mode
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono